name: msi-zarr-analysis
channels:
  - defaults
dependencies:
  - python
  - conda-forge::click
  - conda-forge::ipython
  - conda-forge::jupyter
  - conda-forge::matplotlib
  - conda-forge::numba
  - conda-forge::numpy
  - conda-forge::opencv
  - conda-forge::pandas
  - bioconda::pyimzml
  - conda-forge::rasterio
  - conda-forge::scikit-learn
  - conda-forge::scikit-image
  - conda-forge::zarr
  - conda-forge::pytest
  - pip=23.0.1
  - pip:
    - git+https://github.com/Cytomine-ULiege/Cytomine-python-client@v2.9.0#egg=cytomine-python-client
    - tensorstore==0.1.30
